// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgxgH68LQzRgTz_dbuk_N92How5KuBfc',
    appId: '1:466912463502:web:2458f5fa0e77949ce557df',
    messagingSenderId: '466912463502',
    projectId: 'anix-b211f',
    authDomain: 'anix-b211f.firebaseapp.com',
    storageBucket: 'anix-b211f.firebasestorage.app',
    measurementId: 'G-2ZVTFVDTNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDof21lHoGJsdfv5LEowSAxgnHk_OZGWsg',
    appId: '1:466912463502:android:86f63ecb2e8ebb72e557df',
    messagingSenderId: '466912463502',
    projectId: 'anix-b211f',
    storageBucket: 'anix-b211f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3GGG6rDceQPuJBByMe1IwxrGwvK3WKJg',
    appId: '1:466912463502:ios:3a906b3c677f7aade557df',
    messagingSenderId: '466912463502',
    projectId: 'anix-b211f',
    storageBucket: 'anix-b211f.firebasestorage.app',
    iosBundleId: 'com.example.anix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3GGG6rDceQPuJBByMe1IwxrGwvK3WKJg',
    appId: '1:466912463502:ios:3a906b3c677f7aade557df',
    messagingSenderId: '466912463502',
    projectId: 'anix-b211f',
    storageBucket: 'anix-b211f.firebasestorage.app',
    iosBundleId: 'com.example.anix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgxgH68LQzRgTz_dbuk_N92How5KuBfc',
    appId: '1:466912463502:web:51e30493e9105da3e557df',
    messagingSenderId: '466912463502',
    projectId: 'anix-b211f',
    authDomain: 'anix-b211f.firebaseapp.com',
    storageBucket: 'anix-b211f.firebasestorage.app',
    measurementId: 'G-PVLDBV5QTB',
  );
}
